[package]
name = "rust-car"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.5.0"
libipld = "0.13.1"
libipld-cbor = "0.13.1"
thiserror = "1.0.31"
unsigned-varint = "0.7.1"
