[package]
name = "rust-racecar"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.5.0"
libipld = "0.16.0"
thiserror = "1.0.31"
unsigned-varint = "0.7.1"
